version: '3.8'

services:
  trustmanager:
    image: eclipseaerios/trust-manager:latest
    #build: .
    container_name: trustmanager
    ports:
      - "3000:3000"
    volumes:
      - ./configs/manager.ini:/manager/configs/manager.ini:ro
   

