replicaCount: 1

image:
  repository: eclipseaerios/trust-manager
  tag: ""
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000
  name: api
  protocol: TCP

resources:
  requests:
    memory: "100Mi"
    cpu: "100m"
  limits:
    memory: "1000Mi"
    cpu: "1000m"

nodeSelector: {}
tolerations: []
affinity: {}

configManagerIni: |
  [General]
  port = 3000
  storageName = scores
  storageReset = no

  [Connections]
  domain = MyDomain
  ngsild_cb_url = orion-ld-broker.default.svc.cluster.local:1026
  iota_api_url = iota-api.default.svc.cluster.local:6000
  iota_node_ip = iota-hornet.default.svc.cluster.local
  log_file_port = 8000

  [TrustAlgorithm]
  scoreInterval = 120
  reliabilityInterval = 20
  reputationInterval = 7
  healthPenalty = 0.01
  ReliabilityWeight = 0.5
  SecurityWeight = 0.3
  ReputationWeight = 0.2
  priorityThreshold = 3
  notificationThreshold = 10

  [ReliabilityScore]
  cpuCores = +0.2
  currentCpuUsage = -0.2
  ramCapacity = +0.1
  availableRam = +0.25
  currentRamUsage = -0.25

  [SecurityScore]
  priority_1 = 0.25
  priority_2 = 0.35
  priority_3 = 0.4

  [ReputationScore]
  priority_1 = 0.25
  priority_2 = 0.35
  priority_3 = 0.4
