apiVersion: v1
kind: Service
metadata:
  name: trustmanager
spec:
  type: ClusterIP
  selector:
    app: trustmanager
  clusterIP: 10.254.102.73
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: api
